sistema_os/ordens/urls.py
from django.urls import path
from ordens.views import home, create, edit, verify_os, edit_step, edit_step_add_pictures, edit_step_relatorio, edit_step_add_final_pictures

app_name = 'ordens'

urlpatterns = [
    path('', home, name='home'),  
    path('create/', create, name='create'),  
    path('edit/<int:os_number>/', edit, name='edit'),  
    path('edit/<int:os_number>/add_pictures', edit_step_add_pictures, name='add_pictures'),  
    path('edit/<int:os_number>/relatorio', edit_step_relatorio, name='relatorio'),  
    path('edit/<int:os_number>/final_pictures', edit_step_add_final_pictures, name='add_final_pictures'),  
    path('edit_step/', edit_step, name='edit_step'),  
    path('verify_os/', verify_os, name='verificar_os'),
]

sistema_os/sistema_os/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('ordens.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema_os/ordens/models.py
from django.db import models

# Create your models here.

sistema_os/ordens/views.py
from django.shortcuts import render, redirect
from ordens.utils.locate_os import check_existing
from ordens.utils.create_folders import create_folder, save_imgs
from django.http import JsonResponse, Http404
from django.contrib import messages
from django.conf import settings
import os



# Create your views here.
def home(request):
    if request.method == 'POST':
        os_number = request.POST.get('os-number')
        if check_existing(os_number):
            return(redirect('ordens:edit', os_number))
        else:
            messages.warning(request, f'OS {os_number} não existe')            
            
                
    return render(request, 'ordens/pages/index.html',
                  context={'window_title': 'Início',})
    

def create(request):
    if request.method == 'POST':
        number = request.POST.get('os-number')
        created = create_folder(request.POST, request.FILES)
        if created:
            messages.success(request, f'OS {number} criada com sucesso!')
            return redirect('ordens:home')
        
        else:
            messages.error(request, 'Algo deu errado, tente novamente')
    
    return render(request, 'ordens/pages/create.html',
                  context={'window_title': 'Criando OS'})
    
    
def edit(request, os_number):
    if request.method == 'POST':
        edits_chosen = request.POST.getlist('edit_options', [])
        
        if not edits_chosen:
            messages.error(request, 'Selecione ao menos uma etapa')
            return redirect('ordens:edit', os_number)
        
        request.session['edit_steps'] = edits_chosen
        request.session['edit_index'] = 0
        request.session['os_number'] = os_number
        
        return redirect('ordens:edit_step')
 
    return render(request, 'ordens/pages/edit.html',
                  context={'window_title': 'Criando OS',
                           'os_number': os_number})
    

def edit_step(request):
    steps = request.session.get('edit_steps', [])
    index = request.session.get('edit_index', 0)
    os_number = request.session.get('os_number')
    
    if index >= len(steps):
        messages.success(request, f'OS {os_number} editada com sucesso')
        return redirect('ordens:home')
    
    current_step = steps[index]
    return redirect(f'ordens:{current_step}', os_number=os_number)


def edit_step_add_pictures(request, os_number):
    if request.method == 'POST':
        full_path = os.path.join(settings.CAMINHO_BASE_SALVAMENTO, str(os_number))
        save_imgs(full_path, os_number, request.FILES)
        
        request.session['edit_index'] += 1
        return redirect('ordens:edit_step')

    return render(request, 'ordens/pages/edits/pictures.html')


def edit_step_relatorio(request, os_number):
    if request.method == 'POST':
        
        
        request.session['edit_index'] += 1
        return redirect('ordens:edit_step')
    
    return render(request, 'ordens/pages/edits/relatorio.html')


def edit_step_add_final_pictures(request, os_number):
    if request.method == 'POST':
        
        
        request.session['edit_index'] += 1
        return redirect('ordens:edit_step')
    
    return render(request, 'ordens/pages/edits/final_pictures.html')


def verify_os(request):
    numero_os = request.GET.get('os_number')
    existe = check_existing(numero_os)
    return JsonResponse({'existe': existe})

sistema_os/ordens/templates/ordens/pages/create.html
{% load static %}
{% include "global/partials/head.html" %}
<link rel="stylesheet" href="{% static "ordens/css/create.css" %}">
<link rel="stylesheet" href="{% static "ordens/css/input_file.css" %}">
</head>
<body>
    {% include "global/partials/messages.html" %}
    
    {% include "global/partials/header.html" %}

    <main>
        <h2>Dados do equipamento</h2>

        <form action="" id='main-form' method='post' enctype="multipart/form-data">
            {% csrf_token %}
            <span class='input-span os-number'>
                <span class='os-error' id='os-error'>Número de OS já cadastrado</span>
                <input type="text" inputmode="numeric" pattern="[0-9]*" name="os-number" id="os-number" placeholder="Digite o número da OS" onblur='verificarNumeroOS()' required>
            </span>
            
            <span class='input-span client'>
                <input type="text" name="client" id="client" placeholder='Cliente'>
            </span>

            <span class='input-span equipment'>
                <input type="text" name="equipment" id="equiament" placeholder='Equipamento'>
            </span>

            <span class='input-span brand'>
                <input type="text" name="brand" id="brand" placeholder='Marca'>
            </span>

            <span class='input-span pot'>
                <input type="text" inputmode="decimal" pattern="[0-9]*" name="pot" id="pot" placeholder='Potência (CV)'>
            </span>

            <span class='input-span rotation'>
                <input type="text" inputmode="numerci" pattern="[0-9]*" name="rotation" id="rotation" placeholder='RPM'>
            </span>

            <span class='input-span pictures'>
                <label for="pictures" id='label-pictures'>Adicionar imagens</label>
                <input type="file" name="pictures" id="pictures" accept="image/*" multiple placeholder='Fotos do equipamento'>
            </span>
            <div id="pictures-container" class="status"></div>

            <button type="submit" id='confirm' disabled>Confirmar</button>
        </form>

        
    </main>

    {% comment %} <script src="{% static "global/js/auto_update.js" %}"></script> {% endcomment %}
    <script src="{% static "ordens/js/update_pictures.js" %}"></script>
    <script src="{% static "ordens/js/check_os.js" %}"></script>
    
</body>
</html>

sistema_os/ordens/templates/ordens/pages/edit.html
{% load static %}
    {% include "global/partials/head.html" %}
    <link rel="stylesheet" href="{% static "ordens/css/edit.css" %}">
</head>
<body>
    {% include "global/partials/messages.html" %}
    
    {% include "global/partials/header.html" %}

    <main>
        <h2>Editando a OS {{ os_number }}</h2>
        <p>Selecione as alterações que deseja fazer</p>

        <form action="" method='POST'>
            {% csrf_token %}

            <span>
                <input type="checkbox" name="edit_options" id="add_pictures" value="add_pictures">
                <label class='label-option' for="add_pictures">Adicionar imagens de entrada</label>
            </span>

            <span>
                <input type="checkbox" name="edit_options" id="relatorio" value="relatorio">
                <label class='label-option' for="relatorio">Adicionar relatório de testes</label>
            </span>

            <span>
                <input type="checkbox" name="edit_options" id="add_final_pictures" value="add_final_pictures">
                <label class='label-option' for="add_final_pictures">Adicionar fotos de saída</label>
            </span>


            <button type="submit">Confirmar</button>
        </form>
    </main>




    {% comment %} <script src="{% static "global/js/auto_update.js" %}"></script> {% endcomment %}
</body>
</html>

sistema_os/ordens/templates/ordens/pages/edits/final_pictures.html
{% load static %}
{% include "global/partials/head.html" %}
</head>
<body>
    {% include "global/partials/messages.html" %}
    {% include "global/partials/header.html" %}
    final pictures
</body>
</html>

sistema_os/ordens/templates/ordens/pages/edits/laudo.html
{% load static %}
{% include "global/partials/head.html" %}
</head>
<body>
    {% include "global/partials/messages.html" %}
    {% include "global/partials/header.html" %}
    laudo
</body>
</html>

sistema_os/ordens/templates/ordens/pages/edits/pictures.html
{% load static %}
{% include "global/partials/head.html" %}
</head>
<body>
    {% include "global/partials/messages.html" %}
    {% include "global/partials/header.html" %}
    <link rel="stylesheet" href="{% static "ordens/css/input_file.css" %}">
    <link rel="stylesheet" href="{% static "ordens/css/edits/pictures.css" %}">
    <main>
    <h2>Adicionando novas fotos</h2>
        <form action="" method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            <span class='input-span pictures'>
                <label for="pictures" id='label-pictures'>Adicionar imagens</label>
                <input type="file" name="pictures" id="pictures" accept="image/*" multiple placeholder='Fotos do equipamento'>
            </span>
            <div id="pictures-container" class="status"></div>

            <div class="action-buttons">
                <button class='action-button' type="submit">Confirmar</button>
            </div>
        </form>
    </main>

    <script src="{% static "ordens/js/update_pictures.js" %}"></script>
</body>
</html>

sistema_os/ordens/templates/ordens/pages/edits/relatorio.html
{% load static %}
{% include "global/partials/head.html" %}
</head>
<body>
    {% include "global/partials/messages.html" %}
    {% include "global/partials/header.html" %}
    relatorio
</body>
</html>

sistema_os/ordens/templates/ordens/pages/index.html
{% load static %} 

{% include "global/partials/head.html" %}
    <link rel="stylesheet" href="{% static "ordens/css/index.css" %}">
</head>
<body>
    {% include "global/partials/messages.html" %}
    
    {% include "global/partials/header.html" %}

    <main>
        <h1>Você deseja:</h1>
        <div class="options">
            <a href="{% url "ordens:create" %}" class='option-button'>Cadastrar uma nova OS</a>
            <button id='edit-os' class='option-button'>Editar uma OS existente</button>
            <form action="" method='post' id="form-os-number">
                {% csrf_token %}
                <input type="text" inputmode="numeric" pattern="[0-9]*" name="os-number" id="os-number" placeholder="Digite o número da OS" value='{{ os_number }}'>
                <button type="submit"><i class="fa-solid fa-check"></i></button>
            </form>
        </div>
    </main>


    {% include "global/partials/footer.html" %}
          
    <script src="{% static "ordens/js/toggle_visibility.js" %}"></script>
</body>
</html>

sistema_os/templates/global/partials/footer.html
   <footer>
        
    </footer>

sistema_os/templates/global/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{ window_title }} </title>
    <link rel="stylesheet" href="{% static "global/css/style.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Almarai:wght@300;400;700&family=Outfit:wght@100..900&family=Roboto:ital,wght@0,100..900;1,100..900&family=Syne:wght@400..800&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1c1371ef50.js" crossorigin="anonymous"></script>

sistema_os/templates/global/partials/header.html
{% load static %}
    <header>
        <a href="{% url "ordens:home" %}"><img src="{% static "global/images/gomu-gomu.png" %}" alt=""></a>
    </header>

sistema_os/templates/global/partials/messages.html
{% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">
                    <i class="fa-solid fa-xmark"></i>
                </span>
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}